// Lottery

export const GET_PROVINCES = 'GET_PROVINCES';
export const GET_NORTH_LOTTERIES = 'GET_NORTH_LOTTERIES';

export const LOADING_PROVINCES = 'LOADING_PROVINCES';
export const FAILED_LOAD_PROVINCES = 'FAILED_LOAD_PROVINCES';