// User
export const GET_USERS = 'GET_USERS';
export const LOADING_USERS = 'LOADING_USERS';
export const FAILED_LOAD_USERS = 'FAILED_LOAD_USERS';

// Lottery
export const GET_PROVINCES = 'GET_PROVINCES';
export const GET_NORTH_LOTTERIES = 'GET_NORTH_LOTTERIES';

export const LOADING_PROVINCES = 'LOADING_PROVINCES';
export const FAILED_LOAD_PROVINCES = 'FAILED_LOAD_PROVINCES';